export const API_BASE_URL = 'http://localhost:8080/api/v1';
export const ROLE_VALUES = { CUSTOMER: 'CUSTOMER', HOTEL_MANAGER: 'HOTEL_MANAGER', ADMIN: 'ADMIN', GUEST: 'GUEST' };
export const BOOKING_STATUS = { CONFIRMED: 'CONFIRMED', PENDING: 'PENDING', CANCELLED: 'CANCELLED' };
export const SERVICE_TYPES = ['BAR', 'RESTAURANT', 'CAR_HIRE', 'SPA', 'LOCAL_TOUR'];
